version: '3.6'
services:
  nginx:
    image: systimax/otustest:docker-nginx-php
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    #volumes:
    #     - ./www/html/:/var/www/html/
    volumes:
#      - type: tmpfs
#        source: /dev/shm
#        target: /var/www/html/
    - php::/var/www/html/

   

  php:
    image: systimax/otustest:docker-php
    container_name: php-container
    
    #ports:
    #   – 9000
    #volumes:
    #      - ./www/html/:/var/www/html/
    volumes:
      - type: tmpfs
#        source: /dev/shm
        target: /var/www/html/

